name = "Modpack Server Trm"
author = "Tifeko"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75aecd3ba3f31af5a317383e8d5673cfa5e532368e85640a4f85c874f3992a41"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
