name = "Modpack Server Trm"
author = "Tifeko"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a201265e24a303b98db26bca954c31acc7cbcbb3ed4a8d9317c91f902ca6013"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
