name = "Modpack Server Trm"
author = "Tifeko"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39a12c10a21e10beee86972027f32a68f1f5f9723ddfdeee087be63f5759e156"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
