name: Packwiz modrinth Export & Release
on: [push, workflow_dispatch]
jobs:
  export-to-modrinth:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: wget "https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip"
      - run: unzip "Linux 64-bit x86.zip"
      - run: chmod +x packwiz
      - run: sudo mv packwiz /usr/bin/
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: cd ${{ github.workspace }}
      - run: packwiz modrinth export -o modpack.mrpack
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{github.workspace }}/modpack.mrpack
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{github.workspace }}/modpack.mrpack
          tag_name: "${{ github.run_id }}"