name: Packwiz modrinth Export & Release
on: [push, workflow_dispatch]
jobs:
  export-to-modrinth:
    runs-on: ubuntu-latest
    steps:
      - run: wget "https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip"
      - run: unzip "Linux 64-bit x86.zip"
      - run: chmod +x packwiz
      - run: mv packwiz /usr/bin/
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: cd ${{ github.workspace }}
      - run: packwiz modrinth export